version: 2

sources:
    - name: ukraine_tweets_all
      #For bigquery:
      database: massive-tuner-338911
      # For postgres:
      # database: production
      schema: trips_data_all
      # loaded_at_field: record_loaded_at
      tables:
        - name: all_tweets_table
        - name: languages_tags_bcp_47
         # freshness:
           # error_after: {count: 6, period: hour}
